---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-msg
spec:
  hosts:
    - hello-msg
  gateways:
    - mesh
  http:
  - route:
      - destination:
          host: hello-msg
          port:
            number: 8888
          subset: v1
        weight: 30
      - destination:
          host: hello-msg
          port:
            number: 8888
          subset: v2
        weight: 30
      - destination:
          host: hello-msg
          port:
            number: 8888
          subnet: v3
        weight: 40
---
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#  name: hello-msg
#spec:
#  hosts:
#    - hello-msg
#  gateways:
#    - mesh
#  http:
#    - route:
#      - destination:
#          host: hello-msg
#          port:
#            number: 8888
#          subset: v1
#      mirror:
#        host: hello-msg
#        port:
#          number: 8888
#        subset: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-msg
spec:
  host: hello-msg
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-kube
spec:
  host: hello-kube
  subsets:
    - name: v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-kube
spec:
  hosts:
    - hello-kube
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: hello-kube
            port:
              number: 8080
            subset: v1
---