---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-msg
spec:
  hosts:
    - hello-msg
  gateways:
    - mesh
  http:
  - route:
    - destination:
        host: hello-msg
        port:
          number: 8888
        subset: v1
      weight: 50
    - destination:
        host: hello-msg
        port:
          number: 8888
        subset: v2
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-msg
spec:
  host: hello-msg
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: hello-kube
spec:
  host: hello-kube
  subsets:
    - name: v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-kube
spec:
  hosts:
    - hello-kube
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: hello-kube
            port:
              number: 8080
            subset: v1
---